##########################################################################################################################
# File automatically-generated by STM32forVSCode
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#   2024-04-27 - Added env file inclusion. 
#                Added way to overide: build directory, target name and optimisation.
#                Added GCC_PATH by env file to not make the makefile machine dependent.
#                Currently folder structure in build directory is preserved
#                Switching of debug/release build output folder now happens based on debug flag
#   2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# Environment Variables
######################################
# Imports the environment file in which the compiler and other tooling is set
# for the build machine.
# This can also be used to overwrite some makefile variables
file_exists = $(or $(and $(wildcard $(1)),1),0)
ifeq ($(call file_exists,.stm32env),1)
  include .stm32env
endif

######################################
# Target
######################################
# This is the name of the embedded target which will be build
# The final file name will also have debug or release appended to it.
TARGET ?= deltaprobe

#######################################
# Build directories
#######################################
# Build path can be overwritten when calling make or setting the environment variable
# in .stm32env

BUILD_DIRECTORY ?= build


######################################
# Optimization
######################################
# Optimization is switched based upon the DEBUG variable. If set to 1
# it will be build in debug mode with the Og optimization flag (optimized for debugging).
# If set to 0 (false) then by default the variable is used in the configuration yaml
# This can also be overwritten using the environment variable or by overwriting it
# by calling make with the OPTIMIZATION variable e.g.:
# make -f STM32Make.make -j 16  OPTIMIZATION=Os

# variable which determines if it is a debug build
DEBUG ?= 1

# debug flags when debug is defined
OPTIMIZATION ?= -Og

RELEASE_DIRECTORY = $(BUILD_DIRECTORY)/debug
ifeq ($(DEBUG),1)
  # Sets debugging optimization -Og and the debug information output
  OPTIMIZATION_FLAGS += -Og -g -gdwarf -ggdb
  $(TARGET) := $(TARGET)-debug
  RELEASE_DIRECTORY := $(BUILD_DIRECTORY)/debug
else
  OPTIMIZATION_FLAGS += $(OPTIMIZATION)
  $(TARGET) := $(TARGET)-release
  RELEASE_DIRECTORY := $(BUILD_DIRECTORY)/release
endif

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/display.c \
Core/Src/display_assets.c \
Core/Src/flash.c \
Core/Src/main.c \
Core/Src/measure.c \
Core/Src/stm32f4xx_hal_msp.c \
Core/Src/stm32f4xx_it.c \
Core/Src/syscalls.c \
Core/Src/sysmem.c \
Core/Src/system_stm32f4xx.c \
Core/Src/u8g2_stm32f4.c \
Core/Src/usb.c \
Core/Src/usb_descriptors.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c \
Lib/tinyusb/class/audio/audio_device.c \
Lib/tinyusb/class/bth/bth_device.c \
Lib/tinyusb/class/cdc/cdc_device.c \
Lib/tinyusb/class/cdc/cdc_host.c \
Lib/tinyusb/class/dfu/dfu_device.c \
Lib/tinyusb/class/dfu/dfu_rt_device.c \
Lib/tinyusb/class/hid/hid_device.c \
Lib/tinyusb/class/hid/hid_host.c \
Lib/tinyusb/class/midi/midi_device.c \
Lib/tinyusb/class/midi/midi_host.c \
Lib/tinyusb/class/msc/msc_device.c \
Lib/tinyusb/class/msc/msc_host.c \
Lib/tinyusb/class/mtp/mtp_device.c \
Lib/tinyusb/class/net/ecm_rndis_device.c \
Lib/tinyusb/class/net/ncm_device.c \
Lib/tinyusb/class/usbtmc/usbtmc_device.c \
Lib/tinyusb/class/vendor/vendor_device.c \
Lib/tinyusb/class/vendor/vendor_host.c \
Lib/tinyusb/class/video/video_device.c \
Lib/tinyusb/common/tusb_fifo.c \
Lib/tinyusb/device/usbd.c \
Lib/tinyusb/device/usbd_control.c \
Lib/tinyusb/host/hub.c \
Lib/tinyusb/host/usbh.c \
Lib/tinyusb/portable/analog/max3421/hcd_max3421.c \
Lib/tinyusb/portable/bridgetek/ft9xx/dcd_ft9xx.c \
Lib/tinyusb/portable/chipidea/ci_fs/dcd_ci_fs.c \
Lib/tinyusb/portable/chipidea/ci_hs/dcd_ci_hs.c \
Lib/tinyusb/portable/chipidea/ci_hs/hcd_ci_hs.c \
Lib/tinyusb/portable/dialog/da146xx/dcd_da146xx.c \
Lib/tinyusb/portable/ehci/ehci.c \
Lib/tinyusb/portable/mentor/musb/dcd_musb.c \
Lib/tinyusb/portable/mentor/musb/hcd_musb.c \
Lib/tinyusb/portable/microchip/pic/dcd_pic.c \
Lib/tinyusb/portable/microchip/pic32mz/dcd_pic32mz.c \
Lib/tinyusb/portable/microchip/samd/dcd_samd.c \
Lib/tinyusb/portable/microchip/samd/hcd_samd.c \
Lib/tinyusb/portable/microchip/samg/dcd_samg.c \
Lib/tinyusb/portable/microchip/samx7x/dcd_samx7x.c \
Lib/tinyusb/portable/mindmotion/mm32/dcd_mm32f327x_otg.c \
Lib/tinyusb/portable/nordic/nrf5x/dcd_nrf5x.c \
Lib/tinyusb/portable/nuvoton/nuc120/dcd_nuc120.c \
Lib/tinyusb/portable/nuvoton/nuc121/dcd_nuc121.c \
Lib/tinyusb/portable/nuvoton/nuc505/dcd_nuc505.c \
Lib/tinyusb/portable/nxp/khci/dcd_khci.c \
Lib/tinyusb/portable/nxp/khci/hcd_khci.c \
Lib/tinyusb/portable/nxp/lpc17_40/dcd_lpc17_40.c \
Lib/tinyusb/portable/nxp/lpc_ip3511/dcd_lpc_ip3511.c \
Lib/tinyusb/portable/ohci/ohci.c \
Lib/tinyusb/portable/raspberrypi/pio_usb/dcd_pio_usb.c \
Lib/tinyusb/portable/raspberrypi/pio_usb/hcd_pio_usb.c \
Lib/tinyusb/portable/raspberrypi/rp2040/dcd_rp2040.c \
Lib/tinyusb/portable/raspberrypi/rp2040/hcd_rp2040.c \
Lib/tinyusb/portable/raspberrypi/rp2040/rp2040_usb.c \
Lib/tinyusb/portable/renesas/rusb2/dcd_rusb2.c \
Lib/tinyusb/portable/renesas/rusb2/hcd_rusb2.c \
Lib/tinyusb/portable/renesas/rusb2/rusb2_common.c \
Lib/tinyusb/portable/sony/cxd56/dcd_cxd56.c \
Lib/tinyusb/portable/st/stm32_fsdev/dcd_stm32_fsdev.c \
Lib/tinyusb/portable/st/stm32_fsdev/fsdev_common.c \
Lib/tinyusb/portable/st/stm32_fsdev/hcd_stm32_fsdev.c \
Lib/tinyusb/portable/st/typec/typec_stm32.c \
Lib/tinyusb/portable/sunxi/dcd_sunxi_musb.c \
Lib/tinyusb/portable/synopsys/dwc2/dcd_dwc2.c \
Lib/tinyusb/portable/synopsys/dwc2/dwc2_common.c \
Lib/tinyusb/portable/synopsys/dwc2/hcd_dwc2.c \
Lib/tinyusb/portable/template/dcd_template.c \
Lib/tinyusb/portable/template/hcd_template.c \
Lib/tinyusb/portable/ti/msp430x5xx/dcd_msp430x5xx.c \
Lib/tinyusb/portable/valentyusb/eptri/dcd_eptri.c \
Lib/tinyusb/portable/wch/dcd_ch32_usbfs.c \
Lib/tinyusb/portable/wch/dcd_ch32_usbhs.c \
Lib/tinyusb/portable/wch/hcd_ch32_usbfs.c \
Lib/tinyusb/tusb.c \
Lib/tinyusb/typec/usbc.c \
Lib/u8g2/mui.c \
Lib/u8g2/mui_u8g2.c \
Lib/u8g2/u8g2_arc.c \
Lib/u8g2/u8g2_bitmap.c \
Lib/u8g2/u8g2_box.c \
Lib/u8g2/u8g2_buffer.c \
Lib/u8g2/u8g2_button.c \
Lib/u8g2/u8g2_circle.c \
Lib/u8g2/u8g2_cleardisplay.c \
Lib/u8g2/u8g2_d_memory.c \
Lib/u8g2/u8g2_d_setup.c \
Lib/u8g2/u8g2_font.c \
Lib/u8g2/u8g2_fonts.c \
Lib/u8g2/u8g2_hvline.c \
Lib/u8g2/u8g2_input_value.c \
Lib/u8g2/u8g2_intersection.c \
Lib/u8g2/u8g2_kerning.c \
Lib/u8g2/u8g2_line.c \
Lib/u8g2/u8g2_ll_hvline.c \
Lib/u8g2/u8g2_message.c \
Lib/u8g2/u8g2_polygon.c \
Lib/u8g2/u8g2_selection_list.c \
Lib/u8g2/u8g2_setup.c \
Lib/u8g2/u8log.c \
Lib/u8g2/u8log_u8g2.c \
Lib/u8g2/u8log_u8x8.c \
Lib/u8g2/u8x8_8x8.c \
Lib/u8g2/u8x8_byte.c \
Lib/u8g2/u8x8_cad.c \
Lib/u8g2/u8x8_capture.c \
Lib/u8g2/u8x8_d_a2printer.c \
Lib/u8g2/u8x8_d_ch1120.c \
Lib/u8g2/u8x8_d_gp1247ai.c \
Lib/u8g2/u8x8_d_gp1287ai.c \
Lib/u8g2/u8x8_d_gp1294ai.c \
Lib/u8g2/u8x8_d_gu800.c \
Lib/u8g2/u8x8_d_hd44102.c \
Lib/u8g2/u8x8_d_il3820_296x128.c \
Lib/u8g2/u8x8_d_ist3020.c \
Lib/u8g2/u8x8_d_ist3088.c \
Lib/u8g2/u8x8_d_ist7920.c \
Lib/u8g2/u8x8_d_ks0108.c \
Lib/u8g2/u8x8_d_lc7981.c \
Lib/u8g2/u8x8_d_ld7032_60x32.c \
Lib/u8g2/u8x8_d_ls013b7dh03.c \
Lib/u8g2/u8x8_d_max7219.c \
Lib/u8g2/u8x8_d_pcd8544_84x48.c \
Lib/u8g2/u8x8_d_pcf8812.c \
Lib/u8g2/u8x8_d_pcf8814_hx1230.c \
Lib/u8g2/u8x8_d_s1d15300.c \
Lib/u8g2/u8x8_d_s1d15721.c \
Lib/u8g2/u8x8_d_s1d15e06.c \
Lib/u8g2/u8x8_d_sbn1661.c \
Lib/u8g2/u8x8_d_sed1330.c \
Lib/u8g2/u8x8_d_sh1106_64x32.c \
Lib/u8g2/u8x8_d_sh1106_72x40.c \
Lib/u8g2/u8x8_d_sh1107.c \
Lib/u8g2/u8x8_d_sh1108.c \
Lib/u8g2/u8x8_d_sh1122.c \
Lib/u8g2/u8x8_d_ssd1305.c \
Lib/u8g2/u8x8_d_ssd1306_128x32.c \
Lib/u8g2/u8x8_d_ssd1306_128x64_noname.c \
Lib/u8g2/u8x8_d_ssd1306_2040x16.c \
Lib/u8g2/u8x8_d_ssd1306_48x64.c \
Lib/u8g2/u8x8_d_ssd1306_64x32.c \
Lib/u8g2/u8x8_d_ssd1306_64x48.c \
Lib/u8g2/u8x8_d_ssd1306_72x40.c \
Lib/u8g2/u8x8_d_ssd1306_96x16.c \
Lib/u8g2/u8x8_d_ssd1306_96x40.c \
Lib/u8g2/u8x8_d_ssd1309.c \
Lib/u8g2/u8x8_d_ssd1312.c \
Lib/u8g2/u8x8_d_ssd1315_128x64_noname.c \
Lib/u8g2/u8x8_d_ssd1316.c \
Lib/u8g2/u8x8_d_ssd1317.c \
Lib/u8g2/u8x8_d_ssd1318.c \
Lib/u8g2/u8x8_d_ssd1320.c \
Lib/u8g2/u8x8_d_ssd1322.c \
Lib/u8g2/u8x8_d_ssd1325.c \
Lib/u8g2/u8x8_d_ssd1326.c \
Lib/u8g2/u8x8_d_ssd1327.c \
Lib/u8g2/u8x8_d_ssd1329.c \
Lib/u8g2/u8x8_d_ssd1362.c \
Lib/u8g2/u8x8_d_ssd1363.c \
Lib/u8g2/u8x8_d_ssd1606_172x72.c \
Lib/u8g2/u8x8_d_ssd1607_200x200.c \
Lib/u8g2/u8x8_d_st7302.c \
Lib/u8g2/u8x8_d_st7305.c \
Lib/u8g2/u8x8_d_st7511.c \
Lib/u8g2/u8x8_d_st75160.c \
Lib/u8g2/u8x8_d_st75161.c \
Lib/u8g2/u8x8_d_st75256.c \
Lib/u8g2/u8x8_d_st7528.c \
Lib/u8g2/u8x8_d_st75320.c \
Lib/u8g2/u8x8_d_st7539.c \
Lib/u8g2/u8x8_d_st7565.c \
Lib/u8g2/u8x8_d_st7567.c \
Lib/u8g2/u8x8_d_st7571.c \
Lib/u8g2/u8x8_d_st7586s_erc240160.c \
Lib/u8g2/u8x8_d_st7586s_jlx320160.c \
Lib/u8g2/u8x8_d_st7586s_jlx384160.c \
Lib/u8g2/u8x8_d_st7586s_md240128.c \
Lib/u8g2/u8x8_d_st7586s_s028hn118a.c \
Lib/u8g2/u8x8_d_st7586s_ymc240160.c \
Lib/u8g2/u8x8_d_st7588.c \
Lib/u8g2/u8x8_d_st7920.c \
Lib/u8g2/u8x8_d_stdio.c \
Lib/u8g2/u8x8_d_t6963.c \
Lib/u8g2/u8x8_d_uc1601.c \
Lib/u8g2/u8x8_d_uc1604.c \
Lib/u8g2/u8x8_d_uc1608.c \
Lib/u8g2/u8x8_d_uc1609.c \
Lib/u8g2/u8x8_d_uc1610.c \
Lib/u8g2/u8x8_d_uc1611.c \
Lib/u8g2/u8x8_d_uc1617.c \
Lib/u8g2/u8x8_d_uc1628.c \
Lib/u8g2/u8x8_d_uc1638.c \
Lib/u8g2/u8x8_d_uc1698.c \
Lib/u8g2/u8x8_d_uc1701_dogs102.c \
Lib/u8g2/u8x8_d_uc1701_mini12864.c \
Lib/u8g2/u8x8_debounce.c \
Lib/u8g2/u8x8_display.c \
Lib/u8g2/u8x8_fonts.c \
Lib/u8g2/u8x8_gpio.c \
Lib/u8g2/u8x8_input_value.c \
Lib/u8g2/u8x8_message.c \
Lib/u8g2/u8x8_selection_list.c \
Lib/u8g2/u8x8_setup.c \
Lib/u8g2/u8x8_string.c \
Lib/u8g2/u8x8_u16toa.c \
Lib/u8g2/u8x8_u8toa.c


CXX_SOURCES = \


# ASM sources
ASM_SOURCES =  \
startup_stm32f411xe.s


#######################################
# Tools
#######################################
ARM_PREFIX = arm-none-eabi-
POSTFIX = "
PREFIX = "
# The gcc compiler bin path can be defined in the make command via ARM_GCC_PATH variable (e.g.: make ARM_GCC_PATH=xxx)
# or it can be added to the PATH environment variable.
# By default the variable be used from the environment file: .stm32env.
# if it is not defined

ifdef ARM_GCC_PATH
    CC = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)gcc$(POSTFIX)
    CXX = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)g++$(POSTFIX)
    AS = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)gcc$(POSTFIX) -x assembler-with-cpp
    CP = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)objcopy$(POSTFIX)
    SZ = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)size$(POSTFIX)
    DP = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)objdump$(POSTFIX)
else
  CC ?= $(ARM_PREFIX)gcc
  CXX ?= $(ARM_PREFIX)g++$
  AS ?= $(ARM_PREFIX)gcc -x assembler-with-cpp
  CP ?= $(ARM_PREFIX)objcopy
  SZ ?= $(ARM_PREFIX)size
  DP ?= $(ARM_PREFIX)objdump
endif

HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
LSS = $(DP) -h -S


REMOVE_DIRECTORY_COMMAND = rm -fR
mkdir_function = mkdir -p $(1)
ifeq ($(OS),Windows_NT)
  convert_to_windows_path = $(strip $(subst /,\,$(patsubst %/,%,$(1))))
  REMOVE_DIRECTORY_COMMAND = cmd /c rd /s /q
  mkdir_function = cmd /e:on /c if not exist $(call convert_to_windows_path,$(1)) md $(call convert_to_windows_path,$(1))
endif


# Flash and debug tools
# Default is openocd however will be gotten from the env file when existing
OPENOCD ?= openocd


#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DSTM32F411xE \
-DUSE_HAL_DRIVER


# CXX defines
CXX_DEFS =  \
-DSTM32F411xE \
-DUSE_HAL_DRIVER


# AS includes
AS_INCLUDES = \

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/CMSIS/Device/ST/STM32F4xx/Include \
-IDrivers/CMSIS/Include \
-IDrivers/STM32F4xx_HAL_Driver/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy \
-ILib/tinyusb \
-ILib/tinyusb/class/audio \
-ILib/tinyusb/class/bth \
-ILib/tinyusb/class/cdc \
-ILib/tinyusb/class/cdc/serial \
-ILib/tinyusb/class/dfu \
-ILib/tinyusb/class/hid \
-ILib/tinyusb/class/midi \
-ILib/tinyusb/class/msc \
-ILib/tinyusb/class/mtp \
-ILib/tinyusb/class/net \
-ILib/tinyusb/class/usbtmc \
-ILib/tinyusb/class/vendor \
-ILib/tinyusb/class/video \
-ILib/tinyusb/common \
-ILib/tinyusb/device \
-ILib/tinyusb/host \
-ILib/tinyusb/osal \
-ILib/tinyusb/portable/analog/max3421 \
-ILib/tinyusb/portable/chipidea/ci_fs \
-ILib/tinyusb/portable/chipidea/ci_hs \
-ILib/tinyusb/portable/ehci \
-ILib/tinyusb/portable/mentor/musb \
-ILib/tinyusb/portable/microchip/pic32mz \
-ILib/tinyusb/portable/microchip/samx7x \
-ILib/tinyusb/portable/nxp/lpc17_40 \
-ILib/tinyusb/portable/ohci \
-ILib/tinyusb/portable/raspberrypi/rp2040 \
-ILib/tinyusb/portable/renesas/rusb2 \
-ILib/tinyusb/portable/st/stm32_fsdev \
-ILib/tinyusb/portable/sunxi \
-ILib/tinyusb/portable/synopsys/dwc2 \
-ILib/tinyusb/portable/valentyusb/eptri \
-ILib/tinyusb/portable/wch \
-ILib/tinyusb/typec \
-ILib/u8g2



# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(C_INCLUDES) $(C_DEFS) $(OPTIMIZATION_FLAGS) 

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPTIMIZATION_FLAGS)

CXXFLAGS = $(MCU) $(CXX_DEFS) $(C_INCLUDES) $(OPTIMIZATION_FLAGS)

# Add additional flags
CFLAGS += -Wall -fdata-sections -ffunction-sections 
ASFLAGS += -Wall -fdata-sections -ffunction-sections 
CXXFLAGS += -fno-exceptions -fno-rtti 

# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"
CXXFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"

# Output a list file for the compiled source file.
# This is a representative of the source code in assembly
ASSEMBLER_LIST_OUTPUT_FLAG = -Wa,-a,-ad,-alms=$(call add_release_directory,$<,lst)
CFLAGS += $(ASSEMBLER_LIST_OUTPUT_FLAG)
CXXFLAGS += $(ASSEMBLER_LIST_OUTPUT_FLAG)

#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F411XX_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = \
-LLib/u8g2 \
-Ltinyusb


# Additional LD Flags from config file
ADDITIONALLDFLAGS = -Wl,--print-memory-usage -specs=nano.specs 

LDFLAGS = $(MCU) $(ADDITIONALLDFLAGS) -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIRECTORY)/$(TARGET).map,--cref -Wl,--gc-sections

#######################################
# build the application
#######################################
add_release_directory = $(sort $(addprefix $(RELEASE_DIRECTORY)/,$(addsuffix .$(2),$(basename $(notdir $(1))))))



OBJECTS = $(call add_release_directory,$(C_SOURCES),o)
OBJECTS += $(call add_release_directory,$(CXX_SOURCES),o)
OBJECTS += $(call add_release_directory,$(ASM_SOURCES),o)
vpath %.c $(sort $(dir $(C_SOURCES)))
vpath %.cc $(sort $(dir $(CXX_SOURCES)))
vpath %.cp $(sort $(dir $(CXX_SOURCES)))
vpath %.cxx $(sort $(dir $(CXX_SOURCES)))
vpath %.cpp $(sort $(dir $(CXX_SOURCES)))
vpath %.c++ $(sort $(dir $(CXX_SOURCES)))
vpath %.C $(sort $(dir $(CXX_SOURCES)))
vpath %.CPP $(sort $(dir $(CXX_SOURCES)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
vpath %.S $(sort $(dir $(ASM_SOURCES)))

#######################################
# all
#######################################
# note needs to be located as the first rule to be the default build rule
# default action: build all
all: $(RELEASE_DIRECTORY)/$(TARGET).elf $(RELEASE_DIRECTORY)/$(TARGET).hex $(RELEASE_DIRECTORY)/$(TARGET).bin $(RELEASE_DIRECTORY)/$(TARGET).lss 


# C build
$(RELEASE_DIRECTORY)/%.o: %.c STM32Make.make | $(RELEASE_DIRECTORY)
	$(CC) -c $(CFLAGS) $< -o $@

# C++ build 
$(RELEASE_DIRECTORY)/%.o: %.cc STM32Make.make | $(RELEASE_DIRECTORY)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.cp STM32Make.make | $(RELEASE_DIRECTORY)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.cxx STM32Make.make | $(RELEASE_DIRECTORY)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.cpp STM32Make.make | $(RELEASE_DIRECTORY)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.c++ STM32Make.make | $(RELEASE_DIRECTORY)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.C STM32Make.make | $(RELEASE_DIRECTORY)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.CPP STM32Make.make | $(RELEASE_DIRECTORY)
	$(CXX) -c $(CXXFLAGS) $< -o $@

#Assembly build
$(RELEASE_DIRECTORY)/%.o: %.s STM32Make.make | $(RELEASE_DIRECTORY)
	$(AS) -c $(ASFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.S STM32Make.make | $(RELEASE_DIRECTORY)
	$(AS) -c $(ASFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.sx STM32Make.make | $(RELEASE_DIRECTORY)
	$(AS) -c $(ASFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/$(TARGET).elf: $(OBJECTS) STM32Make.make | $(RELEASE_DIRECTORY)
	@echo $(OBJECTS) > $@.in
	$(CC) @$@.in $(LDFLAGS) -o $@
	$(SZ) $@

$(RELEASE_DIRECTORY)/%.hex: $(RELEASE_DIRECTORY)/%.elf | $(RELEASE_DIRECTORY)
	$(HEX) $< $@

$(RELEASE_DIRECTORY)/%.bin: $(RELEASE_DIRECTORY)/%.elf | $(RELEASE_DIRECTORY)
	$(BIN) $< $@

$(RELEASE_DIRECTORY)/%.lss: $(RELEASE_DIRECTORY)/%.elf | $(RELEASE_DIRECTORY)
	$(LSS) $< > $@

$(RELEASE_DIRECTORY):
	$(call mkdir_function, $@)

$(BUILD_DIRECTORY): | $(RELEASE_DIRECTORY)
	$(call mkdir_function, $@)


#######################################
# flash
#######################################
flash: all
	"$(OPENOCD)" -f ./openocd.cfg -c "program $(RELEASE_DIRECTORY)/$(TARGET).elf verify reset exit"

#######################################
# erase
#######################################
erase: all
	"$(OPENOCD)" -f ./openocd.cfg -c "init; reset halt; stm32f4x mass_erase 0; exit"

#######################################
# clean up
#######################################
clean:
	$(REMOVE_DIRECTORY_COMMAND) $(BUILD_DIRECTORY)

#######################################
# custom makefile rules
#######################################

	
#######################################
# dependencies
#######################################
-include $(wildcard $(RELEASE_DIRECTORY)/*.d)

# *** EOF ***