name: Makefile build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install GNU arm embedded toolchain
      uses: carlosperate/arm-none-eabi-gcc-action@v1
    - name: Build
      run: make
